version: 0.2

env:
  variables:
    SONAR_PROJECT_KEY: "AbinashNCI_Elearning"
    SONAR_ORGANIZATION: "AbinashNCI"
    SONAR_HOST_URL: "https://sonarcloud.io"
    SONAR_TOKEN: "9553f786181d4d6c8215a60ee390397f29bbf96f"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt-get update
      - apt-get install -y unzip
      - curl -o /tmp/sonarscanner.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip /tmp/sonarscanner.zip -d /tmp
      - mv /tmp/sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner
      - ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/bin/sonar-scanner
  build:
    commands:
      - sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN