# Generated by Django 5.0.3 on 2024-03-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_created_at_course_instructor_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
    ]
